repos:
  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
        entry: uv run trailing-whitespace-fixer
        language: system
        exclude: ^(.*fits|.*pt|.*pkl|.*npz|.*ckpt|.*png|.*inv|.*npy|.*pdf|.*jpg|.*parquet)
      - id: check-added-large-files
        name: check-added-large-files
        entry: uv run check-added-large-files
        language: system
        args:
          - "--maxkb=15000"
      - id: check-merge-conflict
        name: check-merge-conflict
        entry: uv run check-merge-conflict
        language: system
      - id: end-of-file-fixer
        name: end-of-file-fixer
        entry: uv run end-of-file-fixer
        language: system
        exclude: ^(.*fits|.*pt|.*pkl|.*npz|.*ckpt|.*png|.*inv|.*npy|.*pdf|.*jpg|.*parquet)
      - id: ruff
        name: ruff
        entry: uv run ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        types: [python]
