"""
DES PSF Star Data Loader

This module provides a PyTorch Lightning data module for loading real DES PSF star data
from HDF5 files generated by extract_des_local.py. It offers a similar interface to the
StarDataModule from data_generation.py, making it a replacement for training
models on real astronomical data instead of synthetic data.
"""

import glob
from collections import defaultdict
from pathlib import Path
from typing import List, Optional, Tuple

import h5py
import numpy as np
import pytorch_lightning as pl
import torch
from torch.utils.data import DataLoader, Dataset, Sampler

# Star type encoding
STAR_TYPE_TO_INDEX = {
    "clean": 0,
    "predictor": 1,
    "galaxy": 2,
    "cosmic_ray": 3,
    "padding": 4,
    "unknown": 5,
}


def encode_star_types(star_type_strings):
    """Convert star type strings to uint8 tensor."""
    encoded = []
    for st in star_type_strings:
        if isinstance(st, bytes):
            st = st.decode("utf-8")
        encoded.append(STAR_TYPE_TO_INDEX.get(st, 5))  # 5 for unknown types
    return torch.tensor(encoded, dtype=torch.uint8)


class DESChunkingSampler(Sampler):
    """Custom sampler that groups exposures by file to maximize cache efficiency."""

    def __init__(self, dataset, shuffle: bool = False) -> None:
        super().__init__(data_source=dataset)
        self.dataset = dataset
        self.shuffle = shuffle

    def __len__(self):
        return len(self.dataset)

    def __iter__(self):
        # Group exposure indices by file
        file_groups = defaultdict(list)
        for idx, (file_index, _) in enumerate(self.dataset.exposures):
            file_groups[file_index].append(idx)

        # Create ordering that processes all exposures from each file together
        ordered_indices = []

        if self.shuffle:
            # Shuffle the order of files, but keep exposures within each file together
            file_indices = list(file_groups.keys())
            np.random.shuffle(file_indices)

            for file_idx in file_indices:
                exposure_indices = file_groups[file_idx]
                np.random.shuffle(exposure_indices)  # Shuffle exposures within file
                ordered_indices.extend(exposure_indices)
        else:
            # Process files in order, exposures in order within each file
            for file_idx in sorted(file_groups.keys()):
                ordered_indices.extend(sorted(file_groups[file_idx]))

        return iter(ordered_indices)


class DESDataset(Dataset):
    """
    Dataset class for loading DES PSF star data from HDF5 files.
    """

    def __init__(self, hdf5_files: List[str], r_band_only: bool = True):
        self.hdf5_files = hdf5_files
        self.r_band_only = r_band_only

        # File buffering for efficient access
        self.buffered_file_index = None
        self.buffered_file_data = None

        # Build exposure index
        self.exposures = []  # List of (file_index, exposure_index_in_file)

        print(f"Indexing exposures from {len(self.hdf5_files)} HDF5 files...")

        for file_idx, file_path in enumerate(self.hdf5_files):
            self._index_file_exposures(file_idx, file_path)

        print(f"Loaded {len(self.exposures)} exposures")
        if len(self.exposures) == 0:
            print("Warning: No exposures loaded!")

    def _index_file_exposures(self, file_idx: int, file_path: str) -> None:
        """Index exposures in a single HDF5 file, handling both old and new formats."""
        print(f"  Processing {Path(file_path).name}...")

        with h5py.File(file_path, "r") as f:
            n_exposures = f["cutouts"].shape[0]
            band_array = f["band"][:]

        n_added = 0
        for exp_idx in range(n_exposures):
            exp_bands = [band.decode("utf-8") for band in band_array[exp_idx]]
            r_band_count = sum(1 for band in exp_bands if band == "r")
            if r_band_count > 0:
                self.exposures.append((file_idx, exp_idx))
                n_added += 1

        print(f"    Added {n_added} r-band exposures from {n_exposures} total (new format)")

    def _load_file_data(self, file_index: int):
        """Load and cache data from HDF5 file if not already buffered."""
        if self.buffered_file_index != file_index:
            print(f"Loading file {file_index}: {Path(self.hdf5_files[file_index]).name}")
            self.buffered_file_index = file_index

            # Load exposure-based arrays
            with h5py.File(self.hdf5_files[file_index], "r") as f:
                self.buffered_file_data = {
                    "cutouts": f["cutouts"][:],
                    "flux": f["flux"][:],
                    "x_pixel": f["x_pixel"][:],
                    "y_pixel": f["y_pixel"][:],
                    "band": f["band"][:],
                    "star_type": f["star_type"][:],
                }

            n_exposures = self.buffered_file_data["cutouts"].shape[0]
            print(f"   Loaded {n_exposures} exposures from file")

    def __len__(self):
        return len(self.exposures)

    def __getitem__(
        self, idx: int
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Get exposure data as tensors.

        Returns:
            - cutouts: (n_stars, 32, 32) star image patches
            - flux: (n_stars,) star fluxes
            - positions: (n_stars, 2) pixel positions [x, y]
            - star_types: (n_stars,) encoded star type indices (uint8)
        """
        file_index, exposure_idx = self.exposures[idx]

        # Load file data into buffer if needed
        self._load_file_data(file_index)

        # Extract exposure data
        data = self.buffered_file_data
        cutouts = data["cutouts"][exposure_idx]
        flux = data["flux"][exposure_idx]
        x_pixel = data["x_pixel"][exposure_idx]
        y_pixel = data["y_pixel"][exposure_idx]

        # Handle r-band filtering if requested
        if self.r_band_only:
            bands = data["band"][exposure_idx]
            r_band_mask = np.array(
                [
                    (band.decode("utf-8") if isinstance(band, bytes) else band) == "r"
                    for band in bands
                ]
            )
            # Set non r-band flux to 0
            flux = flux.copy()
            flux[~r_band_mask] = 0.0

        # Convert to tensors
        cutouts_tensor = torch.from_numpy(cutouts.astype(np.float32))
        flux_tensor = torch.from_numpy(flux.astype(np.float32))
        positions_tensor = torch.stack(
            [
                torch.from_numpy(x_pixel.astype(np.float32)),
                torch.from_numpy(y_pixel.astype(np.float32)),
            ],
            dim=1,
        )

        # Encode star types as uint8
        star_types = data["star_type"][exposure_idx]
        star_types_tensor = encode_star_types(star_types)

        return cutouts_tensor, flux_tensor, positions_tensor, star_types_tensor


class DESDataModule(pl.LightningDataModule):
    """
    PyTorch Lightning data module for DES PSF star data.

    This module provides an interface similar to StarDataModule but loads real
    DES PSF star data from HDF5 files.

    Args:
        data_dir: Directory containing DES HDF5 files
        batch_size: Number of exposures per batch
        train_split: Fraction of files to use for training (rest for validation)
        max_files: Maximum number of HDF5 files to use (useful for testing)
        seed: Random seed for file splitting
        num_workers: Number of worker processes for data loading
        r_band_only: Whether to filter to r-band data only
        file_pattern: Glob pattern for finding HDF5 files

    Returns batches of:
        - cutouts: (batch_size, n_stars, 32, 32) star image patches
        - fluxes: (batch_size, n_stars) star fluxes
        - positions: (batch_size, n_stars, 2) pixel positions [x, y]
        - star_types: (batch_size, n_stars) encoded star type indices (uint8)
    """

    def __init__(
        self,
        data_dir: str = "/data/scratch/regier/des_psfs",
        batch_size: int = 32,
        train_split: float = 0.9,
        max_files: Optional[int] = None,
        seed: int = 42,
        num_workers: int = 4,
        r_band_only: bool = True,
        file_pattern: str = "*.h5",
    ):
        super().__init__()
        self.data_dir = data_dir
        self.batch_size = batch_size
        self.train_split = train_split
        self.max_files = max_files
        self.seed = seed
        self.num_workers = num_workers
        self.r_band_only = r_band_only
        self.file_pattern = file_pattern

    def setup(self, stage: Optional[str] = None):
        """Set up train and validation datasets."""
        print(f"Setting up DES data from {self.data_dir}...")

        # Find all HDF5 files using the specified pattern
        hdf5_pattern = str(Path(self.data_dir) / self.file_pattern)
        all_files = sorted(glob.glob(hdf5_pattern))

        if not all_files:
            raise FileNotFoundError(f"No HDF5 files found matching {hdf5_pattern}")

        if self.max_files:
            all_files = all_files[: self.max_files]

        print(f"Found {len(all_files)} HDF5 files")

        # Split files between train and validation
        np.random.seed(self.seed)
        shuffled_files = np.random.permutation(all_files)

        n_train_files = int(len(shuffled_files) * self.train_split)
        train_files = shuffled_files[:n_train_files].tolist()
        val_files = shuffled_files[n_train_files:].tolist()

        print(f"Using {len(train_files)} files for training, {len(val_files)} files for validation")

        # Create datasets
        self.train_dataset = DESDataset(train_files, r_band_only=self.r_band_only)
        self.val_dataset = DESDataset(val_files, r_band_only=self.r_band_only)

        print(f"Training dataset: {len(self.train_dataset)} exposures")
        print(f"Validation dataset: {len(self.val_dataset)} exposures")

    def train_dataloader(self):
        return DataLoader(
            self.train_dataset,
            batch_size=self.batch_size,
            sampler=DESChunkingSampler(self.train_dataset, shuffle=True),
            num_workers=self.num_workers,
            pin_memory=True,
            persistent_workers=True if self.num_workers > 0 else False,
        )

    def val_dataloader(self):
        return DataLoader(
            self.val_dataset,
            batch_size=self.batch_size,
            sampler=DESChunkingSampler(self.val_dataset, shuffle=False),
            num_workers=self.num_workers,
            pin_memory=True,
            persistent_workers=True if self.num_workers > 0 else False,
        )
