"""
DES PSF Star Data Loader

This module provides a PyTorch Lightning data module for loading real DES PSF star data
from HDF5 files generated by extract_des_local.py. It offers a similar interface to the
StarDataModule from data_generation.py, making it a drop-in replacement for training
models on real astronomical data instead of synthetic data.

Key Features:
- Drop-in replacement for StarDataModule
- Loads star cutouts from DES survey data (size determined by data)
- r-band only for simplicity and consistency
- Efficient loading from multiple HDF5 files with caching
- Compatible train/validation split
- Over 1.2 million real PSF stars available

Usage:
    from des_data_loader import DESDataModule

    # Replace StarDataModule with DESDataModule
    data_module = DESDataModule(
        data_dir="/data/scratch/regier/des_psfs",
        batch_size=32,
        train_split=0.9
    )
    data_module.setup()

    # Use exactly like StarDataModule
    train_loader = data_module.train_dataloader()
    for batch in train_loader:
        cutouts, fluxes, positions = batch
        # cutouts: (batch_size, max_stars, H, W) - r-band only, size from data
        # fluxes: (batch_size, max_stars) - padded with zeros
        # positions: (batch_size, max_stars, 2) - padded with zeros
        # Your existing training code works unchanged
"""

import glob
from pathlib import Path
from typing import List, Optional

import h5py
import numpy as np
import pytorch_lightning as pl
import torch
from torch.utils.data import DataLoader, Dataset, Sampler


class DESChunkingSampler(Sampler):
    """Custom sampler that groups exposures by file to maximize cache efficiency."""

    def __init__(self, dataset: "DESDataset", shuffle: bool = False) -> None:
        super().__init__()
        self.dataset = dataset
        self.shuffle = shuffle

    def __len__(self):
        return len(self.dataset)

    def __iter__(self):
        # Group exposure indices by file
        file_groups = {}
        for idx, (file_index, exp_id, star_indices) in enumerate(self.dataset.exposures):
            if file_index not in file_groups:
                file_groups[file_index] = []
            file_groups[file_index].append(idx)

        # Create ordering that processes all exposures from each file together
        ordered_indices = []

        if self.shuffle:
            # Shuffle the order of files, but keep exposures within each file together
            file_indices = list(file_groups.keys())
            np.random.shuffle(file_indices)

            for file_idx in file_indices:
                exposure_indices = file_groups[file_idx]
                np.random.shuffle(exposure_indices)  # Shuffle exposures within file
                ordered_indices.extend(exposure_indices)
        else:
            # Process files in order, exposures in order within each file
            for file_idx in sorted(file_groups.keys()):
                ordered_indices.extend(sorted(file_groups[file_idx]))

        return iter(ordered_indices)


class DESDataset(Dataset):
    """Dataset class for loading DES PSF star data grouped by exposure from HDF5 files with efficient caching."""

    def __init__(self, hdf5_files: List[str], max_stars: int = 512):
        self.hdf5_files = hdf5_files
        self.max_stars = max_stars

        # File buffering similar to ChunkingDataset
        self.buffered_file_index = None
        self.buffered_file_data = None

        # Build exposure index - group all stars by exposure_id
        self.exposures = []  # List of (file_index, exposure_id, indices_in_file)

        print(f"Indexing exposures from {len(self.hdf5_files)} HDF5 files...")

        for file_idx, file_path in enumerate(self.hdf5_files):
            print(f"  Processing {Path(file_path).name}...")
            with h5py.File(file_path, "r") as f:
                # Read exposure table and star exposure indices
                if "exposures" in f:
                    # New format with exposure table
                    exp_table = f["exposures"]
                    exposure_ids = [exp.decode("utf-8") for exp in exp_table["exposure_id"][:]]

                    # Get star data
                    star_exposure_indices = f["exposure_idx"][:]
                    star_bands = [band.decode("utf-8") for band in f["band"][:]]

                    # Filter to r-band stars directly
                    r_band_star_indices = [i for i, band in enumerate(star_bands) if band == "r"]
                    if len(r_band_star_indices) == 0:
                        print(f"    No r-band stars found in {Path(file_path).name}")
                        continue

                    # Map to exposure IDs for r-band stars
                    r_band_star_exposure_ids = [
                        exposure_ids[star_exposure_indices[i]] for i in r_band_star_indices
                    ]

                else:
                    # Legacy format - fallback to old method
                    exposure_ids_raw = f["exposure_id"][:]
                    bands_raw = f["band"][:]

                    # Decode and filter simultaneously
                    exposure_ids = []
                    bands = []
                    r_band_mask = []

                    for i, (exp_raw, band_raw) in enumerate(zip(exposure_ids_raw, bands_raw)):
                        exp_str = exp_raw.decode("utf-8")
                        band_str = band_raw.decode("utf-8")

                        exposure_ids.append(exp_str)
                        bands.append(band_str)
                        r_band_mask.append(band_str == "r")

                    r_band_star_indices = [i for i, is_r in enumerate(r_band_mask) if is_r]
                    r_band_star_exposure_ids = [exposure_ids[i] for i in r_band_star_indices]

                if len(r_band_star_indices) == 0:
                    print(f"    No r-band data found in {Path(file_path).name}")
                    continue

                # Group r-band star indices by exposure_id using dict for efficiency
                exposure_groups = {}
                for local_idx, exp_id in enumerate(r_band_star_exposure_ids):
                    if exp_id not in exposure_groups:
                        exposure_groups[exp_id] = []
                    exposure_groups[exp_id].append(r_band_star_indices[local_idx])

                for exp_id, original_indices in exposure_groups.items():
                    self.exposures.append((file_idx, exp_id, original_indices))

        total_stars = sum(len(indices) for _, _, indices in self.exposures)
        print(f"Loaded {len(self.exposures)} exposures with {total_stars} total stars")
        if len(self.exposures) > 0:
            print(f"Average stars per exposure: {total_stars/len(self.exposures):.1f}")
        else:
            print("Warning: No exposures loaded!")

    def __len__(self):
        return len(self.exposures)

    def _load_file_data(self, file_index: int):
        """Load and cache data from HDF5 file if not already buffered."""
        if self.buffered_file_index != file_index:
            print(f"Loading file {file_index}: {Path(self.hdf5_files[file_index]).name}")
            self.buffered_file_index = file_index

            # Use context manager and read in chunks for better memory management
            with h5py.File(self.hdf5_files[file_index], "r") as f:
                print(f"   Reading cutouts...")
                cutouts = f["cutouts"][:]
                print(f"   Reading flux...")
                flux = f["flux"][:]
                print(f"   Reading positions...")
                x_pixel = f["x_pixel"][:]
                y_pixel = f["y_pixel"][:]

                self.buffered_file_data = {
                    "cutouts": cutouts,
                    "flux": flux,
                    "x_pixel": x_pixel,
                    "y_pixel": y_pixel,
                }

            print(f"   Loaded {len(cutouts)} entries from file")

    def __getitem__(self, idx: int):
        """Get all stars from a single exposure, padded to max_sources."""
        file_index, exposure_id, star_indices = self.exposures[idx]

        # Load file data into buffer if needed
        self._load_file_data(file_index)

        # Access data from buffer
        data = self.buffered_file_data
        n_stars = len(star_indices)

        # Limit to max_stars if needed
        if n_stars > self.max_stars:
            # Take the brightest stars (highest flux)
            fluxes_for_sorting = [data["flux"][i] for i in star_indices]
            sorted_idx = np.argsort(fluxes_for_sorting)[::-1]  # Descending order
            star_indices = [star_indices[i] for i in sorted_idx[: self.max_stars]]
            n_stars = self.max_stars

        # Get patch size from first cutout
        first_cutout = data["cutouts"][star_indices[0]] if star_indices else data["cutouts"][0]
        patch_h, patch_w = first_cutout.shape

        # Initialize padded arrays to max_stars
        fluxes = torch.zeros(self.max_stars, dtype=torch.float32)
        positions = torch.zeros(self.max_stars, 2, dtype=torch.float32)
        cutouts = torch.zeros(self.max_stars, patch_h, patch_w, dtype=torch.float32)

        # Fill in data for actual stars
        for i, star_idx in enumerate(star_indices):
            # Load star data from buffer
            cutout = data["cutouts"][star_idx]
            cutouts[i] = torch.from_numpy(cutout.astype(np.float32))

            fluxes[i] = float(data["flux"][star_idx])
            positions[i, 0] = float(data["x_pixel"][star_idx])
            positions[i, 1] = float(data["y_pixel"][star_idx])

        return cutouts, fluxes, positions


class DESDataModule(pl.LightningDataModule):
    """
    PyTorch Lightning data module for DES PSF star data.

    This module provides an interface similar to StarDataModule but loads real
    DES PSF star data from HDF5 files. Cutout size is determined by the data.

    Args:
        data_dir: Directory containing DES HDF5 files
        max_stars: Maximum stars per exposure (padded/truncated to this)
        batch_size: Number of exposures per batch
        train_split: Fraction of files to use for training (rest for validation)
        max_files: Maximum number of HDF5 files to use (useful for testing)
        seed: Random seed for file splitting
        num_workers: Number of worker processes for data loading

    Returns batches of:
        - cutouts: (batch_size, max_stars, H, W) star image patches (H,W determined by data)
        - fluxes: (batch_size, max_stars) star fluxes (padded with zeros)
        - positions: (batch_size, max_stars, 2) pixel positions [x, y] (padded with zeros)

    Only r-band data is used for simplicity and consistency.
    """

    def __init__(
        self,
        data_dir: str = "/data/scratch/regier/des_psfs",
        max_stars: int = 512,
        batch_size: int = 32,
        train_split: float = 0.9,
        max_files: Optional[int] = None,
        seed: int = 42,
        num_workers: int = 4,
    ):
        super().__init__()
        self.data_dir = data_dir
        self.max_stars = max_stars
        self.batch_size = batch_size
        self.train_split = train_split
        self.max_files = max_files
        self.seed = seed
        self.num_workers = num_workers

    def setup(self, stage=None):
        """Set up train and validation datasets."""
        print(f"Setting up DES data from {self.data_dir}...")

        # Find all HDF5 files
        hdf5_pattern = str(Path(self.data_dir) / "des_psf_stars_*.h5")
        all_files = sorted(glob.glob(hdf5_pattern))

        if not all_files:
            raise FileNotFoundError(f"No HDF5 files found in {self.data_dir}")

        if self.max_files:
            all_files = all_files[: self.max_files]

        print(f"Found {len(all_files)} HDF5 files")

        # Split files between train and validation
        np.random.seed(self.seed)
        shuffled_files = np.random.permutation(all_files)

        n_train_files = int(len(shuffled_files) * self.train_split)
        train_files = shuffled_files[:n_train_files].tolist()
        val_files = shuffled_files[n_train_files:].tolist()

        print(f"Using {len(train_files)} files for training, {len(val_files)} files for validation")

        # Create datasets
        self.train_dataset = DESDataset(train_files, max_stars=self.max_stars)
        self.val_dataset = DESDataset(val_files, max_stars=self.max_stars)

        print(f"Training dataset: {len(self.train_dataset)} exposures")
        print(f"Validation dataset: {len(self.val_dataset)} exposures")

    def train_dataloader(self):
        return DataLoader(
            self.train_dataset,
            batch_size=self.batch_size,
            sampler=DESChunkingSampler(self.train_dataset, shuffle=True),
            num_workers=self.num_workers,
            pin_memory=True,
        )

    def val_dataloader(self):
        return DataLoader(
            self.val_dataset,
            batch_size=self.batch_size,
            sampler=DESChunkingSampler(self.val_dataset, shuffle=False),
            num_workers=self.num_workers,
            pin_memory=True,
        )

    def predict_dataloader(self):
        """Return validation dataloader for predictions."""
        return self.val_dataloader()


def create_compatible_des_dataloader(
    data_dir: str = "/data/scratch/regier/des_psfs",
    max_stars: int = 512,
    batch_size: int = 32,
    max_files: Optional[int] = None,
    **kwargs,
) -> DESDataModule:
    """
    Create a DES data module that's compatible with existing StarDataModule usage.

    Args:
        data_dir: Directory containing DES HDF5 files
        max_stars: Maximum number of stars per exposure (default 512)
        batch_size: Batch size for data loading
        max_files: Maximum number of HDF5 files to use (for testing)
        **kwargs: Additional arguments passed to DESDataModule

    Returns:
        DESDataModule instance ready to use
    """
    return DESDataModule(
        data_dir=data_dir, max_stars=max_stars, batch_size=batch_size, max_files=max_files, **kwargs
    )


if __name__ == "__main__":
    # Example usage
    print("Creating DES data module with exposure-based grouping...")
    data_module = DESDataModule(
        data_dir="/data/scratch/regier/des_psfs",
        max_stars=512,
        batch_size=4,
        max_files=2,  # Use 2 files for testing
        train_split=0.5,  # 50/50 split so we get 1 file for training
    )

    data_module.setup()

    # Print dataset info
    print("\nDataset Information:")
    print(f"  Training exposures: {len(data_module.train_dataset)}")
    print(f"  Validation exposures: {len(data_module.val_dataset)}")
    print(f"  Max stars per exposure: {data_module.max_stars}")

    # Test individual sample first
    print("\nTesting individual exposure sample:")
    sample = data_module.train_dataset[0]
    cutouts, fluxes, positions = sample
    print(f"  Cutouts shape: {cutouts.shape} (max_stars={data_module.max_stars})")
    print(f"  Fluxes shape: {fluxes.shape}")
    print(f"  Positions shape: {positions.shape}")
    print(f"  Actual sources: {torch.sum(fluxes > 0).item()}")
    print(f"  Band: r (filtered)")

    # Test the data loader
    print("\nTesting batch loading:")
    train_loader = data_module.train_dataloader()
    batch = next(iter(train_loader))

    cutouts, fluxes, positions = batch
    print(f"  Batch cutouts shape: {cutouts.shape} (batch_size, max_sources, patch_h, patch_w)")
    print(f"  Batch fluxes shape: {fluxes.shape}")
    print(f"  Batch positions shape: {positions.shape}")

    # Show some statistics
    print(f"\nBatch Statistics:")
    n_sources = [torch.sum(fluxes[i] > 0).item() for i in range(fluxes.shape[0])]
    print(f"  Sources per exposure: {n_sources}")
    print(f"  Total active sources in batch: {sum(n_sources)}")
    print(f"  Band: r-band only")

    # Validate flux ranges
    active_fluxes = fluxes[fluxes > 0]
    if len(active_fluxes) > 0:
        print(f"  Flux range: {active_fluxes.min():.1f} - {active_fluxes.max():.1f}")

    print("\n✅ DES Data Loader test completed successfully!")
    print("   The data loader returns (cutouts, fluxes, positions) for each exposure.")
    print("   Only r-band data is included for simplicity and consistency.")
    print(
        "   This matches the StarDataModule interface where each sample contains multiple sources."
    )
